Removed Travis running quick_test.py because google.appengine.ext.testbed appears to be broken upstream. Travis errors out like so with quick_test.py:
$ python main/runner.py --test-path tests ${HOME}/google-cloud-sdk/
quick_test (unittest.loader._FailedTest) ... ERROR
======================================================================
ERROR: quick_test (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: quick_test
Traceback (most recent call last):
  File "/opt/python/3.6.3/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/python/3.6.3/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/travis/build/gae-init/gae-init/tests/quick_test.py", line 4, in <module>
    from google.appengine.ext import testbed
  File "/home/travis/google-cloud-sdk/platform/google_appengine/google/appengine/ext/testbed/__init__.py", line 120, in <module>
    from google.appengine.api import apiproxy_stub_map
  File "/home/travis/google-cloud-sdk/platform/google_appengine/google/appengine/api/apiproxy_stub_map.py", line 731, in <module>
    apiproxy = GetDefaultAPIProxy()
  File "/home/travis/google-cloud-sdk/platform/google_appengine/google/appengine/api/apiproxy_stub_map.py", line 723, in GetDefaultAPIProxy
    ['apiproxy'])
  File "/home/travis/google-cloud-sdk/platform/google_appengine/google/appengine/runtime/apiproxy.py", line 167
    raise new_exc.__class__, new_exc, tb
                           ^
SyntaxError: invalid syntax