changed instance to F2 changed runtime to python37
ERROR: (gcloud.app.deploy) An error occurred while parsing file: [/Users/nathan/gae/gae-init/main/app.yaml]
libraries entries are only supported by the "python27" runtime
  in "/Users/nathan/gae/gae-init/main/app.yaml", line 72, column 1

removed "libraries" section

ERROR: (gcloud.app.deploy) The [threadsafe] field is specified in file [/Users/nathan/gae/gae-init/main/app.yaml]. This field is not supported with runtime [python37] and can safely be removed.

removed "threadsafe" line

ERROR: (gcloud.app.deploy) skip_files cannot be used with the [python37] runtime. Ignore patterns are instead expressed in a .gcloudignore file. For information on the format and syntax of .gcloudignore files, see https://cloud.google.com/sdk/gcloud/reference/topic/gcloudignore.

Removed the following from app.yaml:
skip_files:
- ^(.*/)?#.*#
- ^(.*/)?.*/RCS/.*
- ^(.*/)?.*\.bak$
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*~
- ^(.*/)?Icon\r
- ^(.*/)?\..*
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^lib/.*
- ^static/dev/.*
- ^static/ext/.*\.coffee
- ^static/ext/.*\.css
- ^static/ext/.*\.js
- ^static/ext/.*\.less
- ^static/ext/.*\.json
- ^static/src/.*
Added main/.gcloudignore with the following:
#*#
*/RCS/*
*.bak
*.pyc
*.pyo
*~
Icon\r
.*
app.yaml
app.yml
index.yaml
index.yml
lib/*
static/dev/*
static/ext/.*.coffee
static/ext/.*.css
static/ext/.*.js
static/ext/.*.less
static/ext/.*.json
static/src/.*

ERROR: (gcloud.app.deploy) INVALID_ARGUMENT: The following fields are not allowed in app.yaml: api_version.

removed "api_version" line from app.yaml

ERROR: (gcloud.app.deploy) INVALID_ARGUMENT: script field for handler '/_ah/stats.*' must be set to 'auto' for runtime python37.

removed "- appstats: on" from app.yaml

ERROR: (gcloud.app.deploy) INVALID_ARGUMENT: script field for handler '/_ah/queue/deferred' must be set to 'auto' for runtime python37.

removed "- deferred: on" from app.yaml

ERROR: (gcloud.app.deploy) INVALID_ARGUMENT: script field for handler '/_ah/remote_api(/.*)?' must be set to 'auto' for runtime python37.

removed "- remote_api: on" from app.yaml, as well as "builtins:" since there was nothing left under it

ERROR: (gcloud.app.deploy) INVALID_ARGUMENT: script field for handler '/.*' must be set to 'auto' for runtime python37.

removed all handlers (under "error_handler:" and "handlers:")

And it deployed!
But it doesn't work :-(

from logs:
import flask ModuleNotFoundError: No module named 'flask'

Copied requriements.txt into main/

ModuleNotFoundError: No module named 'urlparse'

Added urlparse to requirements.txt

Ack! pip install requriements takes so long and I don't think it's necessary anymore.
Emptied the contents of requirements.txt, but kept the contents of main/requirements.txt

Error: Could not find a version that satisfies the requirement urlparse (from -r /var/folders/3z/_26pxzns5zg947hszws95j8h0000gq/T/tmpjOPFKK (line 11)) (from versions: )

Oh, I see: urlparse in py2 changed to urllib.parse in py3
Removed urlparse from requirements.txt

Error:
  File "/Users/nathan/gae/gae-init/main/util.py", line 14, in <module>
    from google.appengine.datastore.datastore_query import Cursor

ModuleNotFoundError: No module named 'google'

added "google-cloud==0.34.0" and "google-cloud-vision==0.34.0" to requirements.txt

ModuleNotFoundError: No module named 'google.appengine'

added "google-cloud-datastore==1.7.1" to requirements.txt

same error

added "google-appengine==1.5.1" to requirements.txt
had to go to https://console.cloud.google.com/cloud-build/builds/33d26dcc-7caf-4ef8-b92e-a57df654c73d?project=gae-init-py3
to see the error, ModuleNotFoundError: No module named 'ez_setup'

added "ez_setup==0.9" to reqs

same error

stumbled on a note on the web saying that some other package trys to use setuputils, then falls back on easy_setup
removed ez_setup, added setuputils==40.5.0

same error